environment:
  nodejs_version: 6.5.0

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - cmd: node gulp build

test_script:
  - node --version
  - npm --version
  - cmd: npm test

artifacts:
  - path: build\quirkbot-factory-test-0.0.1-win-ia32
    name: quirkbot-factory-test-0.0.1-win-ia32

deploy:
  provider: S3
  access_key_id:
    secure: AkqgS6TgE6nC0WUZ3nNtqoH1LkPOYhol/bSlMRleKcg=
  secret_access_key:
    secure: 8hFJeMNTHobCOn8OkZirlb3iCEGjUHtxsWSFv3Jo79nklT34asKfOVcFzf3WJ1/B
  bucket: quirkbot-downloads-stage
  region: us-east-1
  set_public: true
  folder: quirkbot-lite-builds
  artifact: quirkbot-factory-test-0.0.1-win-ia32

version: "{build}"